export interface Formula {
  id: string
  price: number
  name: string
  tagline: string
  description: string
  benefits: string[]
  pdfGuide: string
  followUp?: string
  isPopular?: boolean
  isVip?: boolean
  category: 'starter' | 'growth' | 'premium' | 'vip'
}

export const formulas: Formula[] = [
  {
    id: 'starter-10',
    price: 10,
    name: 'Spark',
    tagline: 'L\'étincelle digitale',
    description: 'Lancez-vous avec les fondamentaux. Guide PDF pour maîtriser votre présence sur Instagram.',
    benefits: [
      'Guide PDF : "Les 10 règles d\'or Instagram"',
      'Stratégie de contenu débutant',
      'Checklist d\'optimisation de profil',
      'Accès immédiat après paiement',
    ],
    pdfGuide: 'guide-spark.pdf',
    category: 'starter',
  },
  {
    id: 'starter-15',
    price: 15,
    name: 'Ignite',
    tagline: 'Allumez votre audience',
    description: 'Développez votre audience avec des techniques éprouvées. Guide complet sur l\'algorithme.',
    benefits: [
      'Guide PDF : "Maîtriser l\'Algorithme"',
      'Stratégie d\'hashtags avancée',
      'Templates de captions haute performance',
      'Planning éditorial 30 jours',
    ],
    pdfGuide: 'guide-ignite.pdf',
    category: 'starter',
  },
  {
    id: 'starter-20',
    price: 20,
    name: 'Rise',
    tagline: 'Montez en puissance',
    description: 'Stratégies d\'engagement et de croissance organique pour doubler votre audience.',
    benefits: [
      'Guide PDF : "Croissance Organique x2"',
      'Analyse de profil & recommandations',
      'Stratégie Reels & Stories',
      'Tableau de bord de suivi de performance',
    ],
    pdfGuide: 'guide-rise.pdf',
    category: 'starter',
  },
  {
    id: 'growth-25',
    price: 25,
    name: 'Surge',
    tagline: 'Le décollage commence ici',
    description: 'Stratégie complète multi-réseaux pour une présence digitale cohérente et percutante.',
    benefits: [
      'Guide PDF : "Stratégie Multi-Réseaux"',
      'Calendrier de contenu personnalisé',
      'Scripts de storytelling captivant',
      'Analyse de vos concurrents (méthode incluse)',
    ],
    pdfGuide: 'guide-surge.pdf',
    category: 'growth',
  },
  {
    id: 'growth-30',
    price: 30,
    name: 'Elevate',
    tagline: 'Élevez votre marque',
    description: 'Construisez une identité de marque forte et reconnaissable sur tous vos réseaux.',
    benefits: [
      'Guide PDF : "Personal Branding Expert"',
      'Kit de charte visuelle DIY',
      'Stratégie de bio optimisée',
      '50 idées de contenu viral',
    ],
    pdfGuide: 'guide-elevate.pdf',
    category: 'growth',
  },
  {
    id: 'growth-40',
    price: 40,
    name: 'Momentum',
    tagline: 'Construisez l\'élan',
    description: 'Technique avancée de monétisation et de conversion de votre audience en clients.',
    benefits: [
      'Guide PDF : "Monétiser son Audience"',
      'Funnel de vente social media',
      'Scripts de prospection DM',
      'Stratégie de partenariats & collaborations',
    ],
    pdfGuide: 'guide-momentum.pdf',
    category: 'growth',
    isPopular: true,
  },
  {
    id: 'growth-50',
    price: 50,
    name: 'Amplify',
    tagline: 'Amplifiez chaque signal',
    description: 'Pack complet pour créateurs de contenu ambitieux visant 10k+ abonnés rapidement.',
    benefits: [
      'Guide PDF : "De 0 à 10K Abonnés"',
      'Stratégie ads organiques TikTok/IG',
      'Template de media kit professionnel',
      'Analyse & audit de votre compte',
    ],
    pdfGuide: 'guide-amplify.pdf',
    category: 'growth',
  },
  {
    id: 'premium-75',
    price: 75,
    name: 'Accelerate',
    tagline: 'Passez la vitesse supérieure',
    description: 'Stratégie d\'accélération premium pour atteindre 50K+ abonnés et générer des revenus.',
    benefits: [
      'Guide PDF Premium : "Accélération Digitale"',
      'Blueprint de croissance sur 90 jours',
      'Stratégie de contenu viral certifiée',
      'Méthode de personal branding haut niveau',
      'Accès à la communauté privée',
    ],
    pdfGuide: 'guide-accelerate.pdf',
    category: 'premium',
  },
  {
    id: 'premium-100',
    price: 100,
    name: 'Dominate',
    tagline: 'Dominez votre niche',
    description: 'Le guide ultime pour devenir une référence incontournable dans votre secteur.',
    benefits: [
      'Guide PDF Premium : "Domination de Niche"',
      'Stratégie complète sur 6 mois',
      'Blueprint de monétisation avancé',
      'Système de délégation & automation',
      'Accès à la boîte à outils exclusive',
    ],
    pdfGuide: 'guide-dominate.pdf',
    category: 'premium',
  },
  {
    id: 'vip-150',
    price: 150,
    name: 'Launch VIP',
    tagline: 'Le suivi qui change tout',
    description: 'Guidé PDF + 1 semaine de suivi personnalisé. Vos questions, nos réponses.',
    benefits: [
      'Tous les guides PDF Premium',
      '1 semaine de suivi personnalisé',
      'Audit complet de votre profil',
      'Stratégie sur-mesure rédigée pour vous',
      '2 sessions feedback par message',
    ],
    pdfGuide: 'guide-launch-vip.pdf',
    followUp: '1 semaine de suivi inclus',
    category: 'vip',
  },
  {
    id: 'vip-300',
    price: 300,
    name: 'Growth VIP',
    tagline: 'Accompagnement bi-mensuel',
    description: 'Deux semaines d\'accompagnement intensif pour transformer radicalement votre présence.',
    benefits: [
      'Tous les guides PDF Premium',
      '2 semaines de suivi personnalisé',
      'Stratégie de croissance sur-mesure',
      'Création de contenus guidée',
      '5 sessions feedback & ajustement',
      'Support prioritaire 7j/7',
    ],
    pdfGuide: 'guide-growth-vip.pdf',
    followUp: '2 semaines de suivi intensif',
    category: 'vip',
    isPopular: true,
  },
  {
    id: 'vip-500',
    price: 500,
    name: 'Scale VIP',
    tagline: 'Un mois pour tout changer',
    description: '1 mois d\'accompagnement complet pour scaler votre business digital comme un pro.',
    benefits: [
      'Tous les guides PDF Premium',
      '1 mois de suivi personnalisé complet',
      'Stratégie business digitale avancée',
      'Sessions hebdomadaires de coaching',
      'Plan de monétisation détaillé',
      'Création de système de revenus passifs',
      'Support illimité pendant la période',
    ],
    pdfGuide: 'guide-scale-vip.pdf',
    followUp: '1 mois de suivi complet',
    category: 'vip',
  },
  {
    id: 'vip-1000',
    price: 1000,
    name: 'Empire VIP',
    tagline: 'L\'accompagnement d\'élite',
    description: 'Accompagnement VIP avancé pour ceux qui veulent construire un empire digital.',
    benefits: [
      'Tous les guides PDF Premium + exclusifs',
      'Accompagnement VIP sur-mesure complet',
      'Stratégie d\'empire digital personnalisée',
      'Sessions de coaching illimitées',
      'Accès direct 24/7 pendant 3 mois',
      'Co-création de votre système de vente',
      'Plan de délégation & team building',
      'Réseau de contacts privilégiés',
    ],
    pdfGuide: 'guide-empire-vip.pdf',
    followUp: 'Accompagnement VIP avancé 3 mois',
    category: 'vip',
    isVip: true,
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Sophie Laurent',
    role: 'Créatrice de contenu lifestyle',
    avatar: 'SL',
    rating: 5,
    text: 'MMI Boost m\'a transformé. En 6 semaines, je suis passée de 800 à 12 000 abonnés sur Instagram. Les stratégies sont concrètes, actionables et vraiment efficaces. Je recommande les yeux fermés !',
    formula: 'Growth VIP – £300',
    growth: '+1400%',
  },
  {
    id: 2,
    name: 'Marcus Chen',
    role: 'Coach business en ligne',
    avatar: 'MC',
    rating: 5,
    text: 'Le guide Dominate a complètement changé mon approche du marketing digital. J\'ai enfin compris comment monétiser mon audience. Mon CA a doublé en 2 mois.',
    formula: 'Dominate – £100',
    growth: '+200% CA',
  },
  {
    id: 3,
    name: 'Yasmine Duval',
    role: 'Entrepreneuse e-commerce',
    avatar: 'YD',
    rating: 5,
    text: 'L\'accompagnement Scale VIP vaut chaque centime. J\'avais une boutique en ligne qui stagnait. Aujourd\'hui j\'ai un flux constant de clients grâce aux réseaux. Incroyable !',
    formula: 'Scale VIP – £500',
    growth: '+340% de ventes',
  },
  {
    id: 4,
    name: 'Thomas Moreau',
    role: 'Photographe freelance',
    avatar: 'TM',
    rating: 5,
    text: 'Pour £40, le guide Momentum m\'a donné plus de valeur que des formations à 500€. J\'ai compris comment attirer mes clients idéaux sur Instagram. Mes demandes ont explosé.',
    formula: 'Momentum – £40',
    growth: '+180% demandes',
  },
  {
    id: 5,
    name: 'Amina Diallo',
    role: 'Thérapeute holistique',
    avatar: 'AD',
    rating: 5,
    text: 'L\'Empire VIP est l\'investissement le plus rentable de ma carrière. 3 mois d\'accompagnement intensif et j\'ai construit une audience engagée de 25 000 personnes. Merci MMI Boost !',
    formula: 'Empire VIP – £1000',
    growth: '25K abonnés',
  },
  {
    id: 6,
    name: 'Kevin Rousseau',
    role: 'Consultant en finance',
    avatar: 'KR',
    rating: 5,
    text: 'J\'étais sceptique au début. Mais dès le premier guide, j\'ai vu que c\'était du sérieux. Des stratégies concrètes, basées sur des données réelles. Mon engagement a triplé en un mois.',
    formula: 'Surge – £25',
    growth: '+300% engagement',
  },
]

export const faqs = [
  {
    question: 'Est-ce que les guides PDF sont accessibles immédiatement ?',
    answer: 'Oui, dès la confirmation de votre paiement, vous recevez un lien de téléchargement instantané par email. Les guides sont disponibles 24/7 et sans limite de temps.',
  },
  {
    question: 'En quoi consiste le suivi personnalisé des offres VIP ?',
    answer: 'Pour les offres au-dessus de £100, vous bénéficiez d\'un suivi personnalisé avec notre équipe. Cela inclut des sessions de feedback, une stratégie sur-mesure rédigée pour vous, et un support prioritaire pendant toute la durée du suivi.',
  },
  {
    question: 'Quels réseaux sociaux sont couverts par vos stratégies ?',
    answer: 'Nos guides et stratégies couvrent principalement Instagram, TikTok, LinkedIn, YouTube et Twitter/X. Nous nous adaptons à votre secteur d\'activité et à votre audience cible.',
  },
  {
    question: 'Puis-je acheter plusieurs formules ?',
    answer: 'Absolument ! Beaucoup de nos clients commencent par une formule d\'entrée pour se familiariser, puis évoluent vers un accompagnement VIP. Toutes vos ressources sont cumulables.',
  },
  {
    question: 'Y a-t-il une garantie satisfait ou remboursé ?',
    answer: 'Nous offrons une garantie satisfait ou remboursé de 7 jours sur tous nos guides PDF. Pour les accompagnements VIP, nous évaluons chaque situation individuellement pour garantir votre satisfaction.',
  },
  {
    question: 'Je suis débutant, par où commencer ?',
    answer: 'Nous recommandons de commencer par la formule Spark (£10) ou Ignite (£15) pour poser les bases. Notre guide Surge (£25) est idéal si vous souhaitez aller plus vite. Contactez-nous si vous avez un doute.',
  },
  {
    question: 'Les formules VIP incluent-elles du coaching en visioconférence ?',
    answer: 'Les suivis se font principalement par messages et feedback écrit détaillé, ce qui permet une réponse plus réfléchie et documentée. Pour les formules £500 et £1000, des sessions spéciales peuvent être organisées.',
  },
  {
    question: 'Comment sont calculés les résultats mis en avant ?',
    answer: 'Les chiffres partagés sont des résultats réels de clients qui ont appliqué nos stratégies. Les résultats varient selon le secteur, la régularité d\'application et la niche. Nous ne promettons pas de résultats garantis.',
  },
]
